version: 0.0
os: linux
files:
 - source: .
   destination: /var/www/html/
hooks:
 AfterInstall:
  - location: scripts/httpd_start.sh
    timeout: 300
    runas: root
 ValidateService:
  - location: scripts/httpd_restart.sh
    timeout: 300
    runas: root
